**This notebook is an exercise in the [Pandas](https://www.kaggle.com/learn/pandas) course.  You can reference the tutorial at [this link](https://www.kaggle.com/residentmario/summary-functions-and-maps).**

---

# Introduction

Now you are ready to get a deeper understanding of your data.

Run the following cell to load your data and some utility functions (including code to check your answers).

In [4]:
import pandas as pd
pd.set_option("display.max_rows", 20)
reviews = pd.read_csv("./data/wine-reviews/winemag-data-130k-v2.csv", index_col=0)

____ = None

reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,60,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

# Exercises

## 1.

What is the median of the `points` column in the `reviews` DataFrame?

In [6]:
median_points = ____

# Check your answer
median_points

88.0

## 2. 
What countries are represented in the dataset? (Your answer should not include any duplicates.)

In [ ]:
countries = ____

# Check your answer
countries

## 3.
How often does each country appear in the dataset? Create a Series `reviews_per_country` mapping countries to the count of reviews of wines from that country.

In [ ]:
reviews_per_country = ____

# Check your answer
reviews_per_country

## 4.
Create variable `centered_price` containing a version of the `price` column with the mean price subtracted.

(Note: this 'centering' transformation is a common preprocessing step before applying various machine learning algorithms.)

In [ ]:
centered_price = ____

# Check your answer
centered_price

## 5.
I'm an economical wine buyer. Which wine is the "best bargain"? Create a variable `bargain_wine` with the title of the wine with the highest points-to-price ratio in the dataset.

In [ ]:
bargain_wine = ____

# Check your answer
bargain_wine

## 6.
There are only so many words you can use when describing a bottle of wine. Is a wine more likely to be "tropical" or "fruity"? Create a Series `descriptor_counts` counting how many times each of these two words appears in the `description` column in the dataset. (For simplicity, let's ignore the capitalized versions of these words.)

In [ ]:
descriptor_counts = ____

# Check your answer
descriptor_counts

## 7.
We'd like to host these wine reviews on our website, but a rating system ranging from 80 to 100 points is too hard to understand - we'd like to translate them into simple star ratings. A score of 95 or higher counts as 3 stars, a score of at least 85 but less than 95 is 2 stars. Any other score is 1 star.

Also, the Canadian Vintners Association bought a lot of ads on the site, so any wines from Canada should automatically get 3 stars, regardless of points.

Create a series `star_ratings` with the number of stars corresponding to each review in the dataset.

In [ ]:
# star_ratings = reviews.points.map(lambda p: 3 if p >= 95 else (2 if p >= 85 else 1))
def start_calculation(wine_row):
  if wine_row.country == "Canada":
    return 3
  return 3 if wine_row.points >= 95 else (2 if wine_row.points >= 85 else 1)

reviews["stars"] = reviews.apply(start_calculation, axis="columns")

# Check your answer

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,stars
454,Canada,"An aromatic knockout with notes of peach, papa...",Reserve Icewine,92,30.0,Ontario,Niagara-On-The-Lake,NaN,Sean P. Sullivan,@wawinereport,Pillitteri 2012 Reserve Icewine Vidal (Niagara...,Vidal,Pillitteri,3
2616,Canada,"A slightly earthy, spicy nose leads, followed ...",Fusion,83,12.0,Ontario,Niagara Peninsula,NaN,Susan Kostrzewa,@suskostrzewa,Pillitteri 2004 Fusion Gewürztraminer-Riesling...,Gewürztraminer-Riesling,Pillitteri,3
5129,Canada,The Okanagan has the capability to produce del...,NaN,92,32.0,British Columbia,Okanagan Valley,NaN,Paul Gregutt,@paulgwine,Burrowing Owl 2014 Pinot Noir (Okanagan Valley),Pinot Noir,Burrowing Owl,3
5253,Canada,A fine companion to the winery's Cabernet Sauv...,NaN,91,38.0,British Columbia,Okanagan Valley,NaN,Paul Gregutt,@paulgwine,Burrowing Owl 2013 Cabernet Franc (Okanagan Va...,Cabernet Franc,Burrowing Owl,3
5580,Canada,"Intense flavors of mango, melon and apricot le...",Select Late Harvest,87,24.0,Ontario,Niagara Peninsula,NaN,Susan Kostrzewa,@suskostrzewa,Pillitteri 2004 Select Late Harvest Riesling (...,Riesling,Pillitteri,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129117,Canada,This young wine is still pulling itself togeth...,NaN,87,19.0,British Columbia,Okanagan Valley,NaN,Paul Gregutt,@paulgwine,Tinhorn Creek 2013 Chardonnay (Okanagan Valley),Chardonnay,Tinhorn Creek,3
129471,Canada,Coming from five different vineyards across th...,NaN,88,13.0,Ontario,Niagara Peninsula,NaN,Sean P. Sullivan,@wawinereport,Cave Spring 2011 Riesling (Niagara Peninsula),Riesling,Cave Spring,3
129485,Canada,A youthful and appealing wine with notes of or...,Icewine,88,50.0,Ontario,Short Hills Bench,NaN,Sean P. Sullivan,@wawinereport,Henry of Pelham 2012 Icewine Riesling (Short H...,Riesling,Henry of Pelham,3
129528,Canada,A delicious though somewhat reserved wine with...,Icewine,89,45.0,Ontario,Niagara Peninsula,NaN,Sean P. Sullivan,@wawinereport,Henry of Pelham 2011 Icewine Vidal (Niagara Pe...,Vidal,Henry of Pelham,3
129581,Canada,"Smooth and engaging, this offers classic varie...",NaN,90,38.0,British Columbia,Okanagan Valley,NaN,Paul Gregutt,@paulgwine,Burrowing Owl 2013 Syrah (Okanagan Valley),Syrah,Burrowing Owl,3

In [15]:
reviews.loc[reviews.stars == 3].points

345       100
346        98
347        97
348        97
349        97
         ...
129117     87
129471     88
129485     88
129528     89
129581     90
Name: points, Length: 2673, dtype: int64